### ISSUE TITLE
ISO8601 Timezone Offset

### ISSUE THREAD

**Issue by frezik** [ikr/tv4-formats#13]
ISO8601 allows the offset to be specified as "00:00", "0000", or "00". The regex in tv4-formats only allows the first option, with the colon.

This version should allow the other two formats:

`module.exports = /[0-9]{4,}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]+|)(?:[+-][0-9]{2}:?(?:[0-9]{2}|)|Z)/;`

**Comment by ikr** [comment]
Thanks for the input! Just published the v2.0.0 covering that.
