### ISSUE TITLE
Negative duration

### ISSUE THREAD

**Issue by gausie** [ikr/tv4-formats#16]
A lot of systems allow a "negative period" e.g. `-P1D`. Could you support this?

**Comment by ikr** [comment]
Oh, that's an interesting idea. Can you refer me to some of those systems, and maybe give a couple of typical use cases? Because, frankly, the concept of a negative duration seems rather exotic to me. Also I believe it's not covered by the ISO 8601 standard.

**Comment by gausie** [comment]
When you use a duration as a semantic way of describing an offset it makes more sense

- https://github.com/cylc/cylc/wiki/ISO-8601
- http://momentjs.com/docs/#/durations/

**Comment by ikr** [comment]
OK, I see… Where should the minus be? Moment.js puts it in the middle: `PT-6H3M`, and cylc – in the beginning: `-PT6H`

**Comment by gausie** [comment]
I've always seen it at the beginning. I think Moment supports both
positions.

**Comment by ikr** [comment]
Alright, I suggest we add a separate format – `time-offset`. It'll be the same ISO 8601 duration syntax, but allowing `+` and `-` as a prefix. What do you think?

**Comment by gausie** [comment]
Seems reasonable to me!

**Comment by ikr** [comment]
Done. Just published v2.2.0
