### ISSUE TITLE
bower dependency of validator-js vs. webpack - webpack breaks

### ISSUE THREAD

**Issue by simon-scherzinger** [ikr/tv4-formats#23]
Hello Ivan,

I just came across a problem when using tv4-formats with webpack.

In [`index.js`](https://github.com/ikr/tv4-formats/blob/master/index.js#L18) you have the switch for handling npm and bower dependencies of [validator](https://www.npmjs.com/package/validator). The problem I was facing is when webpack tries to resolve all `require` calls it will stop on `validator-js` since it won't find it.

My question to you, would it be possible to remove the switch in `index.js`? Since you don't have a bower package for tv4-formats I'm assuming most (if not all) users of tv4-formats are using the npm version of validator. If some of them don't and use the bower package they should be able to switch to the npm package easily. Of course this will be a breaking change but a version bump to 3.0.0 should be enough for that. ;-)

Let me know what you think and if I can help you with a PR. :-)

Happy coding,

Simon

**Comment by ikr** [comment]
Hi Simon

Yes, I'd drop the bower support like that. A PR is welcome.

Thank you

**Comment by ikr** [comment]
By the way, is it possible to have a test checking that kind of Webpack compatibility? It would be great to add it.

**Comment by simon-scherzinger** [comment]
Hm, the only thing I can come up with is trying to bundle it during the travis build. I think a test in the mocha test suite is not easily done.

Should I add the bundling task to the travis build?

**Comment by ikr** [comment]
Yeah, I think it's an OK option

**Comment by simon-scherzinger** [comment]
released in 3.0.0
